# permissions for end users to view leopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leopod-viewer-role
rules:
- apiGroups:
  - test.leo.io
  resources:
  - leopods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.leo.io
  resources:
  - leopods/status
  verbs:
  - get
